apiVersion: v1
kind: Service
metadata:
  name: neuvector-service-nodeport
spec:
  type: NodePort
  selector:
    "app" : "neuvector-manager-pod"
  ports:
    - protocol: TCP
      port: 443
      targetPort: 8443
