apiVersion: v1
kind: Service
metadata:
  name: neuvector-service-nodeport
spec:
  type: NodePort
  selector:
    release: neuvector
  ports:
    - protocol: TCP
      port: 443
      targetPort: 8443
